services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fullcycle
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    image: muriloscneider/fullcycle-nginx-node-mysql
    build: ./app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 123456
      DB_NAME: fullcycle
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql-data:
